- name: "Create a directory"
  file:
    path: ~/backend
    state: directory
    mode: '0755'

- name: "unzipping"
  unarchive:
    src: artifact.tar.gz
    dest: ~/backend

- name: "Installing Node Dependencies"
  shell: |
    cd ~/backend
    npm install
- name: "pm2"
  shell: |
    cd ~/backend/dist
    pm2 stop default
    pm2 start main.js
  register: execute_node